sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: tLXuD1Kq8zOOUCuZqAzDOJGgwqpUn8bJFzNM3MxTHx0PHKsQ6DYfZqAVvoEC8UvSVJ9o90vfcrvzXd7sU+KunxoGZQsWj+hXicWdwzLK8iaSWvUcnWz761FW0rRkxvLtcRkNwO1fnHfv8ijER8c/RdzNS+QaUUb5zItdc1OTdMo4Iq6ide15N80LnSDe+zO6+Gnp7kWa30fSg1+py4w4fS06p/VbIDwIuIjyIkPbFtV7U2A3bJmGIwXfnn3U14fSMtK+D+AN7KH852JKmiQKkqrtB2nySjSBQfdhnac8RC5y4aiXPVNo7Wuetjrj9RxHjX4PcIfDEGNFlY7JyzvMGhgnEX9JX2VE6pdVmJlG6F7R6vN4gGzvn17ymxtsVPinVoR50rq53vhUvMQzunZEyVvJFgyYEnPmeKPKX7F9cVhv252qdayxteoZPpZpJdghOPf6oIXko/avv9mrOCl2T0YUnQ75xIrEY6SZ5vhLnO+yuylaV9Gd5YPjdKU0ZIbt/ldVBcyf8ChPcChgmvtDtvpEZZjtW+MfKUY9jRbnkh+/yjywR0u3uaCzdtK3CS2+pbQ1mDH05ulpDa52DW0vmQkXvNmdXjn2J+xHOZ5MohT0wul5XUhBffbXTpRru20kdSeyDvdsruPcDLf3HT3Q9qYTR2Oa0tusNAIkD+c7yvE=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Ceres-Runaway-and-Other-Essays_1295
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy